// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Multimodal input modality, shared across engine protos so the servicers can
// route each request to the matching encoder (image vs video vs audio).
type Modality int32

const (
	Modality_MODALITY_UNSPECIFIED Modality = 0
	Modality_IMAGE                Modality = 1
	Modality_AUDIO                Modality = 2
	Modality_VIDEO                Modality = 3
)

// Enum value maps for Modality.
var (
	Modality_name = map[int32]string{
		0: "MODALITY_UNSPECIFIED",
		1: "IMAGE",
		2: "AUDIO",
		3: "VIDEO",
	}
	Modality_value = map[string]int32{
		"MODALITY_UNSPECIFIED": 0,
		"IMAGE":                1,
		"AUDIO":                2,
		"VIDEO":                3,
	}
)

func (x Modality) Enum() *Modality {
	p := new(Modality)
	*p = x
	return p
}

func (x Modality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modality) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Modality) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Modality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modality.Descriptor instead.
func (Modality) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type KvGroupEvent_Operation int32

const (
	KvGroupEvent_INVALID KvGroupEvent_Operation = 0
	KvGroupEvent_STORE   KvGroupEvent_Operation = 1
	KvGroupEvent_REMOVE  KvGroupEvent_Operation = 2
	KvGroupEvent_CLEAR   KvGroupEvent_Operation = 3
)

// Enum value maps for KvGroupEvent_Operation.
var (
	KvGroupEvent_Operation_name = map[int32]string{
		0: "INVALID",
		1: "STORE",
		2: "REMOVE",
		3: "CLEAR",
	}
	KvGroupEvent_Operation_value = map[string]int32{
		"INVALID": 0,
		"STORE":   1,
		"REMOVE":  2,
		"CLEAR":   3,
	}
)

func (x KvGroupEvent_Operation) Enum() *KvGroupEvent_Operation {
	p := new(KvGroupEvent_Operation)
	*p = x
	return p
}

func (x KvGroupEvent_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KvGroupEvent_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (KvGroupEvent_Operation) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x KvGroupEvent_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KvGroupEvent_Operation.Descriptor instead.
func (KvGroupEvent_Operation) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 0}
}

type GetTokenizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenizerRequest) Reset() {
	*x = GetTokenizerRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenizerRequest) ProtoMessage() {}

func (x *GetTokenizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenizerRequest.ProtoReflect.Descriptor instead.
func (*GetTokenizerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type GetTokenizerChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`     // Raw zip bytes (concatenate all chunks)
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"` // SHA-256 fingerprint; set on final chunk only, empty on previous
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenizerChunk) Reset() {
	*x = GetTokenizerChunk{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenizerChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenizerChunk) ProtoMessage() {}

func (x *GetTokenizerChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenizerChunk.ProtoReflect.Descriptor instead.
func (*GetTokenizerChunk) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenizerChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTokenizerChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SubscribeKvEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resume from this sequence number (0 = start from current state).
	StartSequenceNumber uint64 `protobuf:"varint,1,opt,name=start_sequence_number,json=startSequenceNumber,proto3" json:"start_sequence_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeKvEventsRequest) Reset() {
	*x = SubscribeKvEventsRequest{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeKvEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeKvEventsRequest) ProtoMessage() {}

func (x *SubscribeKvEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeKvEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeKvEventsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeKvEventsRequest) GetStartSequenceNumber() uint64 {
	if x != nil {
		return x.StartSequenceNumber
	}
	return 0
}

type KvEventBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Events         []*KvCacheEvent        `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	DpRank         *int32                 `protobuf:"varint,4,opt,name=dp_rank,json=dpRank,proto3,oneof" json:"dp_rank,omitempty"`
	// Group metadata is learned from received events when the engine provides it.
	// Legacy events remain unchanged when unset.
	GroupEventsEnabled bool            `protobuf:"varint,5,opt,name=group_events_enabled,json=groupEventsEnabled,proto3" json:"group_events_enabled,omitempty"`
	GroupEvents        []*KvGroupEvent `protobuf:"bytes,6,rep,name=group_events,json=groupEvents,proto3" json:"group_events,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KvEventBatch) Reset() {
	*x = KvEventBatch{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvEventBatch) ProtoMessage() {}

func (x *KvEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvEventBatch.ProtoReflect.Descriptor instead.
func (*KvEventBatch) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *KvEventBatch) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *KvEventBatch) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KvEventBatch) GetEvents() []*KvCacheEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *KvEventBatch) GetDpRank() int32 {
	if x != nil && x.DpRank != nil {
		return *x.DpRank
	}
	return 0
}

func (x *KvEventBatch) GetGroupEventsEnabled() bool {
	if x != nil {
		return x.GroupEventsEnabled
	}
	return false
}

func (x *KvEventBatch) GetGroupEvents() []*KvGroupEvent {
	if x != nil {
		return x.GroupEvents
	}
	return nil
}

// GPU-local reports, retaining opaque native keys and the complete token span.
// Sparse stores need not contain one hash per token block; no offsets are guessed.
type KvGroupEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Operation       KvGroupEvent_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=smg.grpc.common.KvGroupEvent_Operation" json:"operation,omitempty"`
	GroupId         uint32                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BlockHashes     [][]byte               `protobuf:"bytes,3,rep,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty"`
	ParentBlockHash []byte                 `protobuf:"bytes,4,opt,name=parent_block_hash,json=parentBlockHash,proto3" json:"parent_block_hash,omitempty"`
	TokenIds        []uint32               `protobuf:"varint,5,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	BlockSize       uint32                 `protobuf:"varint,6,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Kind            string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	SlidingWindow   uint32                 `protobuf:"varint,8,opt,name=sliding_window,json=slidingWindow,proto3" json:"sliding_window,omitempty"`
	// False when LoRA or extra hash inputs prevent token-only matching.
	TokensMatchable bool `protobuf:"varint,9,opt,name=tokens_matchable,json=tokensMatchable,proto3" json:"tokens_matchable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KvGroupEvent) Reset() {
	*x = KvGroupEvent{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGroupEvent) ProtoMessage() {}

func (x *KvGroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGroupEvent.ProtoReflect.Descriptor instead.
func (*KvGroupEvent) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *KvGroupEvent) GetOperation() KvGroupEvent_Operation {
	if x != nil {
		return x.Operation
	}
	return KvGroupEvent_INVALID
}

func (x *KvGroupEvent) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *KvGroupEvent) GetBlockHashes() [][]byte {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *KvGroupEvent) GetParentBlockHash() []byte {
	if x != nil {
		return x.ParentBlockHash
	}
	return nil
}

func (x *KvGroupEvent) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *KvGroupEvent) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *KvGroupEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KvGroupEvent) GetSlidingWindow() uint32 {
	if x != nil {
		return x.SlidingWindow
	}
	return 0
}

func (x *KvGroupEvent) GetTokensMatchable() bool {
	if x != nil {
		return x.TokensMatchable
	}
	return false
}

type KvCacheEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*KvCacheEvent_Stored
	//	*KvCacheEvent_Removed
	//	*KvCacheEvent_Cleared
	Data          isKvCacheEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvCacheEvent) Reset() {
	*x = KvCacheEvent{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvCacheEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvCacheEvent) ProtoMessage() {}

func (x *KvCacheEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvCacheEvent.ProtoReflect.Descriptor instead.
func (*KvCacheEvent) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *KvCacheEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *KvCacheEvent) GetData() isKvCacheEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KvCacheEvent) GetStored() *KvBlocksStored {
	if x != nil {
		if x, ok := x.Data.(*KvCacheEvent_Stored); ok {
			return x.Stored
		}
	}
	return nil
}

func (x *KvCacheEvent) GetRemoved() *KvBlocksRemoved {
	if x != nil {
		if x, ok := x.Data.(*KvCacheEvent_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

func (x *KvCacheEvent) GetCleared() *KvCacheCleared {
	if x != nil {
		if x, ok := x.Data.(*KvCacheEvent_Cleared); ok {
			return x.Cleared
		}
	}
	return nil
}

type isKvCacheEvent_Data interface {
	isKvCacheEvent_Data()
}

type KvCacheEvent_Stored struct {
	Stored *KvBlocksStored `protobuf:"bytes,2,opt,name=stored,proto3,oneof"`
}

type KvCacheEvent_Removed struct {
	Removed *KvBlocksRemoved `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

type KvCacheEvent_Cleared struct {
	Cleared *KvCacheCleared `protobuf:"bytes,4,opt,name=cleared,proto3,oneof"`
}

func (*KvCacheEvent_Stored) isKvCacheEvent_Data() {}

func (*KvCacheEvent_Removed) isKvCacheEvent_Data() {}

func (*KvCacheEvent_Cleared) isKvCacheEvent_Data() {}

type KvBlocksStored struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Blocks          []*KvBlock             `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	ParentBlockHash *int64                 `protobuf:"varint,2,opt,name=parent_block_hash,json=parentBlockHash,proto3,oneof" json:"parent_block_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KvBlocksStored) Reset() {
	*x = KvBlocksStored{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvBlocksStored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvBlocksStored) ProtoMessage() {}

func (x *KvBlocksStored) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvBlocksStored.ProtoReflect.Descriptor instead.
func (*KvBlocksStored) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *KvBlocksStored) GetBlocks() []*KvBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *KvBlocksStored) GetParentBlockHash() int64 {
	if x != nil && x.ParentBlockHash != nil {
		return *x.ParentBlockHash
	}
	return 0
}

type KvBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     int64                  `protobuf:"varint,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`
	BlockSize     int32                  `protobuf:"varint,3,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	LoraId        *int64                 `protobuf:"varint,4,opt,name=lora_id,json=loraId,proto3,oneof" json:"lora_id,omitempty"`
	CacheLevel    *int32                 `protobuf:"varint,5,opt,name=cache_level,json=cacheLevel,proto3,oneof" json:"cache_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvBlock) Reset() {
	*x = KvBlock{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvBlock) ProtoMessage() {}

func (x *KvBlock) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvBlock.ProtoReflect.Descriptor instead.
func (*KvBlock) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *KvBlock) GetBlockHash() int64 {
	if x != nil {
		return x.BlockHash
	}
	return 0
}

func (x *KvBlock) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *KvBlock) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *KvBlock) GetLoraId() int64 {
	if x != nil && x.LoraId != nil {
		return *x.LoraId
	}
	return 0
}

func (x *KvBlock) GetCacheLevel() int32 {
	if x != nil && x.CacheLevel != nil {
		return *x.CacheLevel
	}
	return 0
}

type KvBlocksRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHashes   []int64                `protobuf:"varint,1,rep,packed,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty"`
	CacheLevel    *int32                 `protobuf:"varint,2,opt,name=cache_level,json=cacheLevel,proto3,oneof" json:"cache_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvBlocksRemoved) Reset() {
	*x = KvBlocksRemoved{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvBlocksRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvBlocksRemoved) ProtoMessage() {}

func (x *KvBlocksRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvBlocksRemoved.ProtoReflect.Descriptor instead.
func (*KvBlocksRemoved) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *KvBlocksRemoved) GetBlockHashes() []int64 {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *KvBlocksRemoved) GetCacheLevel() int32 {
	if x != nil && x.CacheLevel != nil {
		return *x.CacheLevel
	}
	return 0
}

type KvCacheCleared struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvCacheCleared) Reset() {
	*x = KvCacheCleared{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvCacheCleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvCacheCleared) ProtoMessage() {}

func (x *KvCacheCleared) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvCacheCleared.ProtoReflect.Descriptor instead.
func (*KvCacheCleared) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

type FlushCacheRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seconds to wait for the scheduler to go idle before flushing.
	// 0 = flush immediately (fails if requests are in flight).
	TimeoutS      float32 `protobuf:"fixed32,1,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushCacheRequest) Reset() {
	*x = FlushCacheRequest{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheRequest) ProtoMessage() {}

func (x *FlushCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheRequest.ProtoReflect.Descriptor instead.
func (*FlushCacheRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *FlushCacheRequest) GetTimeoutS() float32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

type FlushCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushCacheResponse) Reset() {
	*x = FlushCacheResponse{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheResponse) ProtoMessage() {}

func (x *FlushCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheResponse.ProtoReflect.Descriptor instead.
func (*FlushCacheResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *FlushCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlushCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory where profiler traces are written (backend default if unset).
	OutputDir *string `protobuf:"bytes,1,opt,name=output_dir,json=outputDir,proto3,oneof" json:"output_dir,omitempty"`
	// Forward step at which profiling starts (immediately if unset).
	StartStep *int32 `protobuf:"varint,2,opt,name=start_step,json=startStep,proto3,oneof" json:"start_step,omitempty"`
	// Number of forward steps to profile (until StopProfile if unset).
	NumSteps *int32 `protobuf:"varint,3,opt,name=num_steps,json=numSteps,proto3,oneof" json:"num_steps,omitempty"`
	// Profiler activities, e.g. "CPU", "GPU", "MEM". Backend default if empty.
	Activities     []string `protobuf:"bytes,4,rep,name=activities,proto3" json:"activities,omitempty"`
	WithStack      *bool    `protobuf:"varint,5,opt,name=with_stack,json=withStack,proto3,oneof" json:"with_stack,omitempty"`
	RecordShapes   *bool    `protobuf:"varint,6,opt,name=record_shapes,json=recordShapes,proto3,oneof" json:"record_shapes,omitempty"`
	ProfileByStage bool     `protobuf:"varint,7,opt,name=profile_by_stage,json=profileByStage,proto3" json:"profile_by_stage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartProfileRequest) Reset() {
	*x = StartProfileRequest{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProfileRequest) ProtoMessage() {}

func (x *StartProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProfileRequest.ProtoReflect.Descriptor instead.
func (*StartProfileRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *StartProfileRequest) GetOutputDir() string {
	if x != nil && x.OutputDir != nil {
		return *x.OutputDir
	}
	return ""
}

func (x *StartProfileRequest) GetStartStep() int32 {
	if x != nil && x.StartStep != nil {
		return *x.StartStep
	}
	return 0
}

func (x *StartProfileRequest) GetNumSteps() int32 {
	if x != nil && x.NumSteps != nil {
		return *x.NumSteps
	}
	return 0
}

func (x *StartProfileRequest) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *StartProfileRequest) GetWithStack() bool {
	if x != nil && x.WithStack != nil {
		return *x.WithStack
	}
	return false
}

func (x *StartProfileRequest) GetRecordShapes() bool {
	if x != nil && x.RecordShapes != nil {
		return *x.RecordShapes
	}
	return false
}

func (x *StartProfileRequest) GetProfileByStage() bool {
	if x != nil {
		return x.ProfileByStage
	}
	return false
}

type StopProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProfileRequest) Reset() {
	*x = StopProfileRequest{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProfileRequest) ProtoMessage() {}

func (x *StopProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProfileRequest.ProtoReflect.Descriptor instead.
func (*StopProfileRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShmHandle struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offset uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Nbytes uint64                 `protobuf:"varint,3,opt,name=nbytes,proto3" json:"nbytes,omitempty"`
	// Producer/lifetime owner. Used by implementations to coordinate cleanup.
	OwnerId       string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShmHandle) Reset() {
	*x = ShmHandle{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShmHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShmHandle) ProtoMessage() {}

func (x *ShmHandle) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShmHandle.ProtoReflect.Descriptor instead.
func (*ShmHandle) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *ShmHandle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShmHandle) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ShmHandle) GetNbytes() uint64 {
	if x != nil {
		return x.Nbytes
	}
	return 0
}

func (x *ShmHandle) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type RemoteTensorHandle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Examples: "nixl", "ucx", "object_store".
	Transport     string `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Descriptor_   []byte `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Nbytes        uint64 `protobuf:"varint,3,opt,name=nbytes,proto3" json:"nbytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteTensorHandle) Reset() {
	*x = RemoteTensorHandle{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteTensorHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteTensorHandle) ProtoMessage() {}

func (x *RemoteTensorHandle) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteTensorHandle.ProtoReflect.Descriptor instead.
func (*RemoteTensorHandle) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *RemoteTensorHandle) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *RemoteTensorHandle) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *RemoteTensorHandle) GetNbytes() uint64 {
	if x != nil {
		return x.Nbytes
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fsmg.grpc.common\"\x15\n" +
	"\x13GetTokenizerRequest\"?\n" +
	"\x11GetTokenizerChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"N\n" +
	"\x18SubscribeKvEventsRequest\x122\n" +
	"\x15start_sequence_number\x18\x01 \x01(\x04R\x13startSequenceNumber\"\xaa\x02\n" +
	"\fKvEventBatch\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x125\n" +
	"\x06events\x18\x03 \x03(\v2\x1d.smg.grpc.common.KvCacheEventR\x06events\x12\x1c\n" +
	"\adp_rank\x18\x04 \x01(\x05H\x00R\x06dpRank\x88\x01\x01\x120\n" +
	"\x14group_events_enabled\x18\x05 \x01(\bR\x12groupEventsEnabled\x12@\n" +
	"\fgroup_events\x18\x06 \x03(\v2\x1d.smg.grpc.common.KvGroupEventR\vgroupEventsB\n" +
	"\n" +
	"\b_dp_rank\"\x9d\x03\n" +
	"\fKvGroupEvent\x12E\n" +
	"\toperation\x18\x01 \x01(\x0e2'.smg.grpc.common.KvGroupEvent.OperationR\toperation\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\rR\agroupId\x12!\n" +
	"\fblock_hashes\x18\x03 \x03(\fR\vblockHashes\x12*\n" +
	"\x11parent_block_hash\x18\x04 \x01(\fR\x0fparentBlockHash\x12\x1b\n" +
	"\ttoken_ids\x18\x05 \x03(\rR\btokenIds\x12\x1d\n" +
	"\n" +
	"block_size\x18\x06 \x01(\rR\tblockSize\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12%\n" +
	"\x0esliding_window\x18\b \x01(\rR\rslidingWindow\x12)\n" +
	"\x10tokens_matchable\x18\t \x01(\bR\x0ftokensMatchable\":\n" +
	"\tOperation\x12\v\n" +
	"\aINVALID\x10\x00\x12\t\n" +
	"\x05STORE\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\x12\t\n" +
	"\x05CLEAR\x10\x03\"\xe7\x01\n" +
	"\fKvCacheEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x129\n" +
	"\x06stored\x18\x02 \x01(\v2\x1f.smg.grpc.common.KvBlocksStoredH\x00R\x06stored\x12<\n" +
	"\aremoved\x18\x03 \x01(\v2 .smg.grpc.common.KvBlocksRemovedH\x00R\aremoved\x12;\n" +
	"\acleared\x18\x04 \x01(\v2\x1f.smg.grpc.common.KvCacheClearedH\x00R\aclearedB\x06\n" +
	"\x04data\"\x89\x01\n" +
	"\x0eKvBlocksStored\x120\n" +
	"\x06blocks\x18\x01 \x03(\v2\x18.smg.grpc.common.KvBlockR\x06blocks\x12/\n" +
	"\x11parent_block_hash\x18\x02 \x01(\x03H\x00R\x0fparentBlockHash\x88\x01\x01B\x14\n" +
	"\x12_parent_block_hash\"\xc4\x01\n" +
	"\aKvBlock\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\x03R\tblockHash\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\x12\x1d\n" +
	"\n" +
	"block_size\x18\x03 \x01(\x05R\tblockSize\x12\x1c\n" +
	"\alora_id\x18\x04 \x01(\x03H\x00R\x06loraId\x88\x01\x01\x12$\n" +
	"\vcache_level\x18\x05 \x01(\x05H\x01R\n" +
	"cacheLevel\x88\x01\x01B\n" +
	"\n" +
	"\b_lora_idB\x0e\n" +
	"\f_cache_level\"j\n" +
	"\x0fKvBlocksRemoved\x12!\n" +
	"\fblock_hashes\x18\x01 \x03(\x03R\vblockHashes\x12$\n" +
	"\vcache_level\x18\x02 \x01(\x05H\x00R\n" +
	"cacheLevel\x88\x01\x01B\x0e\n" +
	"\f_cache_level\"\x10\n" +
	"\x0eKvCacheCleared\"0\n" +
	"\x11FlushCacheRequest\x12\x1b\n" +
	"\ttimeout_s\x18\x01 \x01(\x02R\btimeoutS\"H\n" +
	"\x12FlushCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe4\x02\n" +
	"\x13StartProfileRequest\x12\"\n" +
	"\n" +
	"output_dir\x18\x01 \x01(\tH\x00R\toutputDir\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_step\x18\x02 \x01(\x05H\x01R\tstartStep\x88\x01\x01\x12 \n" +
	"\tnum_steps\x18\x03 \x01(\x05H\x02R\bnumSteps\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"activities\x18\x04 \x03(\tR\n" +
	"activities\x12\"\n" +
	"\n" +
	"with_stack\x18\x05 \x01(\bH\x03R\twithStack\x88\x01\x01\x12(\n" +
	"\rrecord_shapes\x18\x06 \x01(\bH\x04R\frecordShapes\x88\x01\x01\x12(\n" +
	"\x10profile_by_stage\x18\a \x01(\bR\x0eprofileByStageB\r\n" +
	"\v_output_dirB\r\n" +
	"\v_start_stepB\f\n" +
	"\n" +
	"_num_stepsB\r\n" +
	"\v_with_stackB\x10\n" +
	"\x0e_record_shapes\"\x14\n" +
	"\x12StopProfileRequest\"E\n" +
	"\x0fProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\tShmHandle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06nbytes\x18\x03 \x01(\x04R\x06nbytes\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\"j\n" +
	"\x12RemoteTensorHandle\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\fR\n" +
	"descriptor\x12\x16\n" +
	"\x06nbytes\x18\x03 \x01(\x04R\x06nbytes*E\n" +
	"\bModality\x12\x18\n" +
	"\x14MODALITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05AUDIO\x10\x02\x12\t\n" +
	"\x05VIDEO\x10\x03b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_common_proto_goTypes = []any{
	(Modality)(0),                    // 0: smg.grpc.common.Modality
	(KvGroupEvent_Operation)(0),      // 1: smg.grpc.common.KvGroupEvent.Operation
	(*GetTokenizerRequest)(nil),      // 2: smg.grpc.common.GetTokenizerRequest
	(*GetTokenizerChunk)(nil),        // 3: smg.grpc.common.GetTokenizerChunk
	(*SubscribeKvEventsRequest)(nil), // 4: smg.grpc.common.SubscribeKvEventsRequest
	(*KvEventBatch)(nil),             // 5: smg.grpc.common.KvEventBatch
	(*KvGroupEvent)(nil),             // 6: smg.grpc.common.KvGroupEvent
	(*KvCacheEvent)(nil),             // 7: smg.grpc.common.KvCacheEvent
	(*KvBlocksStored)(nil),           // 8: smg.grpc.common.KvBlocksStored
	(*KvBlock)(nil),                  // 9: smg.grpc.common.KvBlock
	(*KvBlocksRemoved)(nil),          // 10: smg.grpc.common.KvBlocksRemoved
	(*KvCacheCleared)(nil),           // 11: smg.grpc.common.KvCacheCleared
	(*FlushCacheRequest)(nil),        // 12: smg.grpc.common.FlushCacheRequest
	(*FlushCacheResponse)(nil),       // 13: smg.grpc.common.FlushCacheResponse
	(*StartProfileRequest)(nil),      // 14: smg.grpc.common.StartProfileRequest
	(*StopProfileRequest)(nil),       // 15: smg.grpc.common.StopProfileRequest
	(*ProfileResponse)(nil),          // 16: smg.grpc.common.ProfileResponse
	(*ShmHandle)(nil),                // 17: smg.grpc.common.ShmHandle
	(*RemoteTensorHandle)(nil),       // 18: smg.grpc.common.RemoteTensorHandle
}
var file_common_proto_depIdxs = []int32{
	7,  // 0: smg.grpc.common.KvEventBatch.events:type_name -> smg.grpc.common.KvCacheEvent
	6,  // 1: smg.grpc.common.KvEventBatch.group_events:type_name -> smg.grpc.common.KvGroupEvent
	1,  // 2: smg.grpc.common.KvGroupEvent.operation:type_name -> smg.grpc.common.KvGroupEvent.Operation
	8,  // 3: smg.grpc.common.KvCacheEvent.stored:type_name -> smg.grpc.common.KvBlocksStored
	10, // 4: smg.grpc.common.KvCacheEvent.removed:type_name -> smg.grpc.common.KvBlocksRemoved
	11, // 5: smg.grpc.common.KvCacheEvent.cleared:type_name -> smg.grpc.common.KvCacheCleared
	9,  // 6: smg.grpc.common.KvBlocksStored.blocks:type_name -> smg.grpc.common.KvBlock
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_proto_msgTypes[5].OneofWrappers = []any{
		(*KvCacheEvent_Stored)(nil),
		(*KvCacheEvent_Removed)(nil),
		(*KvCacheEvent_Cleared)(nil),
	}
	file_common_proto_msgTypes[6].OneofWrappers = []any{}
	file_common_proto_msgTypes[7].OneofWrappers = []any{}
	file_common_proto_msgTypes[8].OneofWrappers = []any{}
	file_common_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
