//! Regenerates `crates/tokenizer/src/native/unicode.rs`: the Unicode class
//! tables the native pre-tokenizer matches with, taken from the regex engine
//! `tokenizers` itself uses (Oniguruma, through `tokenizers::utils::SysRegex`),
//! so the native scanner splits exactly where the Hugging Face pipeline does,
//! at the Unicode version that engine ships.
//!
//! Run: `cargo test -p llm-tokenizer --test gen_unicode_tables -- --ignored --nocapture`
//! and replace the file with the output between the BEGIN and END markers.
#![allow(clippy::expect_used, clippy::print_stdout)]

use tokenizers::utils::SysRegex;

fn matches_whole(re: &SysRegex, text: &str) -> bool {
    re.find_iter(text)
        .next()
        .is_some_and(|(start, end)| start == 0 && end == text.len())
}

fn ranges_of(pattern: &str) -> Vec<(u32, u32)> {
    let re = SysRegex::new(pattern).expect("pattern compiles");
    let mut buf = String::new();
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    for code in 0u32..=0x10FFFF {
        let Some(c) = char::from_u32(code) else {
            continue;
        };
        buf.clear();
        buf.push(c);
        if matches_whole(&re, &buf) {
            match ranges.last_mut() {
                Some((_, end)) if *end + 1 == code => *end = code,
                _ => ranges.push((code, code)),
            }
        }
    }
    ranges
}

#[test]
#[ignore = "generator: prints the Unicode tables for the native pre-tokenizer"]
fn print_unicode_tables() {
    println!("// BEGIN GENERATED");
    println!("//! Unicode class tables for the native pre-tokenizer, generated by");
    println!("//! `tests/gen_unicode_tables.rs` from the regex engine `tokenizers` uses,");
    println!("//! so that `\\p{{L}}`, `\\s` and the rest mean here what they mean there.");
    println!("//! Do not edit by hand; rerun the generator when `tokenizers` updates.");
    println!();
    for (name, pattern) in [
        ("LETTER", r"\p{L}"),
        ("MARK", r"\p{M}"),
        ("NUMBER", r"\p{N}"),
        ("PUNCTUATION", r"\p{P}"),
        ("SYMBOL", r"\p{S}"),
        ("UPPERCASE", r"\p{Lu}"),
        ("LOWERCASE", r"\p{Ll}"),
        ("TITLECASE", r"\p{Lt}"),
        ("MODIFIER_LETTER", r"\p{Lm}"),
        ("OTHER_LETTER", r"\p{Lo}"),
        ("SPACE", r"\s"),
    ] {
        let ranges = ranges_of(pattern);
        println!(
            "/// Code point ranges matching `{pattern}` ({} ranges).",
            ranges.len()
        );
        println!("pub(super) const {name}: &[(u32, u32)] = &[");
        for chunk in ranges.chunks(6) {
            let items: Vec<String> = chunk
                .iter()
                .map(|(a, b)| format!("({a:#x}, {b:#x})"))
                .collect();
            println!("    {},", items.join(", "));
        }
        println!("];");
        println!();
    }
    // Case folding of ASCII letters under `(?i:...)`: every char the engine
    // accepts for each letter, beyond the letter's own two cases.
    println!("/// For each ASCII letter, the non-ASCII characters `(?i:...)` also accepts for it.");
    println!("pub(super) const FOLD_EXTRA: &[(u8, &[char])] = &[");
    for letter in b'a'..=b'z' {
        let pattern = format!("(?i:{})", letter as char);
        let extra: Vec<String> = ranges_of(&pattern)
            .into_iter()
            .flat_map(|(a, b)| a..=b)
            .filter(|&code| code >= 0x80)
            .map(|code| format!("'\\u{{{code:x}}}'"))
            .collect();
        if !extra.is_empty() {
            println!("    (b'{}', &[{}]),", letter as char, extra.join(", "));
        }
    }
    println!("];");
    let apostrophe = ranges_of("(?i:')");
    assert_eq!(apostrophe, vec![(0x27, 0x27)], "apostrophe must not fold");
    println!("// END GENERATED");
}
